spring:
  application:
    name: ecom-api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ecom-order-service
              uri: lb://ecom-order-service
              predicates:
                - Path=/order/**
            - id: ecom-inventory-service
              uri: lb://ecom-inventory-service
              predicates:
                - Path=/inventory/**

server:
  port: 9091
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/